# Generated by Django 2.2.4 on 2019-09-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190201_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('text', 'list')},
        ),
    ]
